version: "1"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=host
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DB=chatdb
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
    ports:
      - "3306:3306"
